// <auto-generated />
namespace Homework_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_manyToMany_ref_in_question_to_test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_manyToMany_ref_in_question_to_test));
        
        string IMigrationMetadata.Id
        {
            get { return "201507121046260_added_manyToMany_ref_in_question_to_test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
