// <auto-generated />
namespace Homework_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Question_test_collection_name_fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Question_test_collection_name_fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201507121113334_Question_test_collection_name_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
